cars=["BMW","Mahindra","Suzuki","Roll Royalce","Bently","Aston Martin","Tata","Audi","Mustang"]
print("________________________________________Append()_______________________________________")
# Append()
cars.append("Ferrari")
print(cars)
print("______________________________________Insert()______________________________________")
# Insert()
cars.insert(3,"porsche")
print(cars)
print("______________________________________sort()______________________________________")
# Sort
cars.sort()
# print(cars.sort(reverse=True))#then return "none" value
print(cars)
print("__________________________________________sort(Descending)________________________")
cars.sort(reverse=True)
print(cars)
print("___________________________________________remove()_________________________")
# remove()
cars.remove("Audi")
print(cars)
print("___________________________________________index()___________________________")
# index()
print(cars.index("Mustang"))
print("___________________________________________extend()___________________________")
# extend()
cars.extend(["Tesla","Nisaan"])
print(cars)
print("___________________________________________pop()_______________________________")
# pop
cars.pop(-1)
print(cars)
print("____________________________________________count()_____________________________")
# count
print(cars.count("BMW"))
print("____________________________________________append multiple()___________________")
# append multiple()
cars.append(["Jaguar","Fiat"])
print(cars)
print("_____________________________________________insert multiple()___________________")
cars.insert(2,["volvo","honda"])
print(cars)
print("______________________________________________find index tata_____________________")
# index(tata)
print(cars.index("Tata"))